version: "3"

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    volumes:
      - ./data/cadastro-api.sql:/docker-entrypoint-initdb.d/cadastro-api.sql

  db-test:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3307:3306"
    volumes:
      - ./data/cadastro-testapi.sql:/docker-entrypoint-initdb.d/cadastro-testapi.sql
